#madlibs game
#fill in the blanks with words
print("Today, I went to the zoo with my (adjective) friend.")
print("We saw a (animal) that could (verb)! It was so (adjective)!")
print("Then, we went to see the (another animal), which was (verb ending in -ing) in the water.") 
print("We ended the day by eating (food) at the snack stand.")
print()
adjective=input("adjective= ")
animal=input("animal: ")
verb=input("verb: ")
adjective2=input("adjective2: ")
another_animal=input("another animal: ")
ing_verb=input("verb ending in -ing: ")
food=input("Food: ")
print ()
print(f"Today, I went to the zoo with my {adjective} friend.")
print(f"We saw a {animal} that could {verb}! It was so {adjective2}!")
print(f"Then, we went to see the {another_animal}, which was {ing_verb} in the water.") 
print(f"We ended the day by eating {food} at the snack stand.")
